kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quotesweb
  labels:
    app: quotesweb
    learn-kubernetes: quotesweb
spec:
  host: quotesweb-254500-magr.apps.exoscale-ch-gva-2-0.appuio.cloud
  to:
    kind: Service
    name: quotesweb
    weight: 100
  port:
    targetPort: 3000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: quotesweb-254500-magr.apps.exoscale-ch-gva-2-0.appuio.cloud
      routerName: default
      conditions:
        - type: Admitted
          status: "True"
          lastTransitionTime: "2025-11-27T12:06:22Z"
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.exoscale-ch-gva-2-0.appuio.cloud
